[workspace]
resolver = "2"
members = [
    "crates/wust",
    "crates/wust-core",
    "crates/wust-codegen",
    "crates/autosynth-isa",
    "crates/autosynth-isa-aarch64",
    "crates/autosynth-isa-riscv64",
    "crates/autosynth-isa-x86_64",
    "crates/autosynth-codegen",
    "crates/autosynth-ir",
    "crates/autosynth-lower",
    "crates/autosynth-backend-aarch64",
    "crates/plasma",
    "crates/plasma_hello", "crates/autosynth-select-aarch64", "crates/autosynth-selector", "crates/autosynth-regalloc", "crates/autosynth-emit-aarch64", "crates/autosynth-emitter", "crates/autosynth-test-utils", "crates/autosynth-graph",
]

[profile.release]
debug = true
