[package]
name = "wust-codegen"
version = "0.1.0"
edition = "2024"

[features]
inspect = ["disarm64"]
trace = ["autosynth-codegen/trace", "autosynth-lower/trace", "autosynth-backend-aarch64/trace"]

[dependencies]
anyhow = "1"
disarm64 = { version = "0.1", optional = true }
libc = "0.2"
wust-core = { path = "../wust-core" }
autosynth-codegen = { path = "../autosynth-codegen" }
autosynth-lower = { path = "../autosynth-lower" }
autosynth-backend-aarch64 = { path = "../autosynth-backend-aarch64" }
autosynth-ir = { path = "../autosynth-ir" }
autosynth-isa = { path = "../autosynth-isa" }
autosynth-regalloc = { path = "../autosynth-regalloc" }

[dev-dependencies]
wat = "1.245.1"
autosynth-select-aarch64 = { path = "../autosynth-select-aarch64" }
autosynth-selector = { path = "../autosynth-selector" }
