[package]
name = "autosynth-backend-aarch64"
version = "0.1.0"
edition = "2024"

[dependencies]
autosynth-backend = { path = "../autosynth-backend" }
autosynth-ir = { path = "../autosynth-ir" }
autosynth-isa = { path = "../autosynth-isa" }
autosynth-isa-aarch64 = { path = "../autosynth-isa-aarch64" }
autosynth-lower = { path = "../autosynth-lower" }
smallvec = "1.10.0"
