import type { ModuleTrace } from './types';

export const mockTrace: ModuleTrace = {
	source: [
		{ pc: 0, text: 'local.get $n', indent: 0, func_index: 0 },
		{ pc: 1, text: 'i32.const 1', indent: 0, func_index: 0 },
		{ pc: 2, text: 'i32.le_s', indent: 0, func_index: 0 },
		{ pc: 3, text: 'if', indent: 0, func_index: 0 },
		{ pc: 4, text: 'local.get $n', indent: 1, func_index: 0 },
		{ pc: 5, text: 'return', indent: 1, func_index: 0 },
		{ pc: 6, text: 'end', indent: 0, func_index: 0 },
		{ pc: 7, text: 'local.get $n', indent: 0, func_index: 0 },
		{ pc: 8, text: 'i32.const 1', indent: 0, func_index: 0 },
		{ pc: 9, text: 'i32.sub', indent: 0, func_index: 0 },
		{ pc: 10, text: 'call $fib', indent: 0, func_index: 0 },
		{ pc: 11, text: 'local.set $a', indent: 0, func_index: 0 },
		{ pc: 12, text: 'local.get $n', indent: 0, func_index: 0 },
		{ pc: 13, text: 'i32.const 2', indent: 0, func_index: 0 },
		{ pc: 14, text: 'i32.sub', indent: 0, func_index: 0 },
		{ pc: 15, text: 'call $fib', indent: 0, func_index: 0 },
		{ pc: 16, text: 'local.set $b', indent: 0, func_index: 0 },
		{ pc: 17, text: 'local.get $a', indent: 0, func_index: 0 },
		{ pc: 18, text: 'local.get $b', indent: 0, func_index: 0 },
		{ pc: 19, text: 'i32.add', indent: 0, func_index: 0 },
		{ pc: 20, text: 'end', indent: 0, func_index: 0 },
	],
	functions: [{
		index: 0,
		name: 'fib',
		params: [{ index: 0, name: '$n', width: 'i32', preg: 'x0' }],
		results: [{ index: 0, width: 'i32', preg: 'x0' }],
		vregs: [
			{ id: 'v0', width: 'i32', target: 'x0' },
			{ id: 'v1', width: 'i32', target: null },
			{ id: 'v2', width: 'i32', target: null },
			{ id: 'v3', width: 'i64', target: 'sp' },
			{ id: 'v4', width: 'i64', target: null },
			{ id: 'v5', width: 'i64', target: 'x30' },
			{ id: 'v6', width: 'i32', target: null },
			{ id: 'v7', width: 'i32', target: null },
			{ id: 'v9', width: 'i32', target: null },
			{ id: 'v10', width: 'i32', target: null },
			{ id: 'v11', width: 'i32', target: null },
			{ id: 'v14', width: 'i32', target: null },
			{ id: 'v16', width: 'i32', target: null },
			{ id: 'v20', width: 'i32', target: null },
			{ id: 'v21', width: 'i32', target: null },
			{ id: 'v26', width: 'i32', target: null },
			{ id: 'v30', width: 'i32', target: null },
		],
		regions: [
			{ id: 'locals', label: 'local', base_preg: 'x29', base_offset: 0 },
			{ id: 'operands', label: 'ops', base_preg: 'x29', base_offset: 24 },
			{ id: 'fibre', label: 'fibre', base_preg: 'sp', base_offset: 0 },
		],
		events: [
			// ---- E0: entry ----
			{ seq: 0, type: 'block_start', block: 'E0', successors: ['U0'] },
			{ seq: 1, type: 'wasm_op', pc: null, label: 'param 0 = i32' },
			{ seq: 2, type: 'define', vreg: 'v0', value: { preg: 'x0' } },
			{ seq: 3, type: 'setslot', vreg: 'v0', region: 'locals', index: 0 },
			{ seq: 4, type: 'wasm_op', pc: null, label: 'local 1 = i32' },
			{ seq: 5, type: 'define', vreg: 'v1', value: { const: 0 } },
			{ seq: 6, type: 'setslot', vreg: 'v1', region: 'locals', index: 1 },
			{ seq: 7, type: 'wasm_op', pc: null, label: 'local 2 = i32' },
			{ seq: 8, type: 'define', vreg: 'v2', value: { const: 0 } },
			{ seq: 9, type: 'setslot', vreg: 'v2', region: 'locals', index: 2 },
			{ seq: 10, type: 'wasm_op', pc: null, label: 'prologue' },
			{ seq: 11, type: 'define', vreg: 'v3', value: { preg: 'sp' } },
			{ seq: 12, type: 'define', vreg: 'v4', value: { const: 16 } },
			{ seq: 13, type: 'ir', inst: { alu: { op: 'sub', dst: 'v3', lhs: 'v3', rhs: 'v4' } } },
			{ seq: 14, type: 'asm', addr: 0x0000, text: 'sub sp, sp, #16', origin: 'lower', parent: 13 },
			{ seq: 15, type: 'define', vreg: 'v5', value: { preg: 'x30' } },
			{ seq: 16, type: 'setslot', vreg: 'v5', region: 'fibre', index: 0 },

			// ---- U0: compare n <= 1 ----
			{ seq: 20, type: 'block_start', block: 'U0', successors: ['U4', 'U6'] },
			{ seq: 21, type: 'wasm_op', pc: 0, label: 'local.get.i32 0' },
			{ seq: 22, type: 'setslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 23, type: 'wasm_op', pc: 1, label: 'i32.const 1' },
			{ seq: 24, type: 'define', vreg: 'v6', value: { const: 1 } },
			{ seq: 25, type: 'setslot', vreg: 'v6', region: 'operands', index: 1 },
			{ seq: 26, type: 'wasm_op', pc: 2, label: 'i32.le_s' },
			{ seq: 27, type: 'clearslot', vreg: 'v6', region: 'operands', index: 1 },
			{ seq: 28, type: 'clearslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 29, type: 'define', vreg: 'v7', value: 'pending' },
			{ seq: 30, type: 'ir', inst: { alu: { op: 'le_s', dst: 'v7', lhs: 'v0', rhs: 'v6' } } },
			{ seq: 31, type: 'asm', addr: 0x0004, text: 'subs w1, w0, #1', origin: 'fuse', parent: 30 },
			{ seq: 32, type: 'setslot', vreg: 'v7', region: 'operands', index: 0 },
			{ seq: 33, type: 'wasm_op', pc: 3, label: 'if' },
			{ seq: 34, type: 'clearslot', vreg: 'v7', region: 'operands', index: 0 },
			{ seq: 35, type: 'ir', inst: { br_if: { cond: 'v7', block_if: 'U4', block_else: 'U6' } } },
			{ seq: 36, type: 'asm', addr: 0x0008, text: 'b.gt U6', origin: 'fuse', parent: 35 },

			// ---- U4: base case return ----
			{ seq: 40, type: 'block_start', block: 'U4', successors: [] },
			{ seq: 41, type: 'wasm_op', pc: 4, label: 'local.get.i32 0' },
			{ seq: 42, type: 'setslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 43, type: 'wasm_op', pc: 5, label: 'return' },
			{ seq: 44, type: 'clearslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 45, type: 'clearslot', vreg: 'v5', region: 'fibre', index: 0 },
			{ seq: 46, type: 'resolve', vreg: 'v5' },
			{ seq: 47, type: 'define', vreg: 'v8', value: { preg: 'sp' } },
			{ seq: 48, type: 'define', vreg: 'v9', value: { const: 16 } },
			{ seq: 49, type: 'ir', inst: { alu: { op: 'add', dst: 'v8', lhs: 'v8', rhs: 'v9' } } },
			{ seq: 50, type: 'asm', addr: 0x000c, text: 'add sp, sp, #16', origin: 'lower', parent: 49 },
			{ seq: 51, type: 'ir', inst: 'ret' },
			{ seq: 52, type: 'asm', addr: 0x0010, text: 'ret', origin: 'lower', parent: 51 },

			// ---- U6: call fib(n-1) ----
			{ seq: 60, type: 'block_start', block: 'U6', successors: ['G0', 'U10'] },
			{ seq: 61, type: 'wasm_op', pc: 7, label: 'local.get.i32 0' },
			{ seq: 62, type: 'setslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 63, type: 'wasm_op', pc: 9, label: 'i32.sub' },
			{ seq: 64, type: 'clearslot', vreg: 'v10', region: 'operands', index: 1 },
			{ seq: 65, type: 'clearslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 66, type: 'define', vreg: 'v11', value: 'pending' },
			{ seq: 67, type: 'ir', inst: { alu: { op: 'sub', dst: 'v11', lhs: 'v0', rhs: 'v10' } } },
			{ seq: 68, type: 'asm', addr: 0x0014, text: 'str w0, [x29]', origin: 'regalloc', parent: 67 },
			{ seq: 69, type: 'asm', addr: 0x0018, text: 'sub w0, w0, #1', origin: 'lower', parent: 67 },
			{ seq: 70, type: 'setslot', vreg: 'v11', region: 'operands', index: 0 },
			{ seq: 71, type: 'wasm_op', pc: 10, label: 'call 0' },
			{ seq: 72, type: 'clearslot', vreg: 'v11', region: 'operands', index: 0 },
			// clobber call
			{ seq: 73, type: 'clobber', vreg: 'v0' },
			{ seq: 74, type: 'clobber', vreg: 'v1' },
			{ seq: 75, type: 'clobber', vreg: 'v2' },
			{ seq: 76, type: 'clobber', vreg: 'v5' },
			{ seq: 77, type: 'asm', addr: 0x001c, text: 'str x30, [sp]', origin: 'regalloc', parent: 76 },
			// advance g.lb
			{ seq: 78, type: 'ir', inst: { alu: { op: 'add', dst: 'v12', lhs: 'v12', rhs: 'v13' } } },
			{ seq: 79, type: 'asm', addr: 0x0020, text: 'add x29, x29, #24', origin: 'lower', parent: 78 },
			{ seq: 80, type: 'ir', inst: { call: { target: 'fib' } } },
			{ seq: 81, type: 'asm', addr: 0x0024, text: 'bl fib', origin: 'lower', parent: 80 },
			// restore g.lb
			{ seq: 82, type: 'ir', inst: { alu: { op: 'sub', dst: 'v14', lhs: 'v14', rhs: 'v15' } } },
			{ seq: 83, type: 'asm', addr: 0x0028, text: 'sub x29, x29, #24', origin: 'lower', parent: 82 },
			// result
			{ seq: 84, type: 'define', vreg: 'v16', value: { preg: 'x0' } },
			{ seq: 85, type: 'setslot', vreg: 'v16', region: 'operands', index: 0 },
			// fuel check
			{ seq: 86, type: 'ir', inst: { alu: { op: 'le_s', dst: 'v17', lhs: 'v17', rhs: 'v18' } } },
			{ seq: 87, type: 'asm', addr: 0x002c, text: 'subs x28, x28, #13', origin: 'fuse', parent: 86 },
			{ seq: 88, type: 'ir', inst: { br_if: { cond: 'v19', block_if: 'G0', block_else: 'U10' } } },
			{ seq: 89, type: 'asm', addr: 0x0030, text: 'b.gt G0', origin: 'fuse', parent: 88 },

			// ---- G0: suspend ----
			{ seq: 100, type: 'block_start', block: 'G0', successors: [] },
			{ seq: 101, type: 'wasm_op', pc: null, label: 'suspend' },
			{ seq: 102, type: 'ir', inst: 'ret' },
			{ seq: 103, type: 'asm', addr: 0x0034, text: 'ret', origin: 'lower', parent: 102 },

			// ---- U10: call fib(n-2) ----
			{ seq: 110, type: 'block_start', block: 'U10', successors: ['G1', 'U15'] },
			{ seq: 111, type: 'wasm_op', pc: 11, label: 'local.set.i32 1' },
			{ seq: 112, type: 'clearslot', vreg: 'v16', region: 'operands', index: 0 },
			{ seq: 113, type: 'clearslot', vreg: 'v1', region: 'locals', index: 1 },
			{ seq: 114, type: 'setslot', vreg: 'v16', region: 'locals', index: 1 },
			{ seq: 115, type: 'wasm_op', pc: 14, label: 'i32.sub' },
			{ seq: 116, type: 'clearslot', vreg: 'v20', region: 'operands', index: 1 },
			{ seq: 117, type: 'clearslot', vreg: 'v0', region: 'operands', index: 0 },
			{ seq: 118, type: 'define', vreg: 'v21', value: 'pending' },
			{ seq: 119, type: 'ir', inst: { alu: { op: 'sub', dst: 'v21', lhs: 'v0', rhs: 'v20' } } },
			{ seq: 120, type: 'asm', addr: 0x0038, text: 'str w0, [x29, #4]', origin: 'regalloc', parent: 119 },
			{ seq: 121, type: 'asm', addr: 0x003c, text: 'ldr w0, [x29]', origin: 'regalloc', parent: 119 },
			{ seq: 122, type: 'asm', addr: 0x0040, text: 'sub w0, w0, #2', origin: 'lower', parent: 119 },
			{ seq: 123, type: 'setslot', vreg: 'v21', region: 'operands', index: 0 },
			{ seq: 124, type: 'wasm_op', pc: 15, label: 'call 0' },
			{ seq: 125, type: 'clearslot', vreg: 'v21', region: 'operands', index: 0 },
			{ seq: 126, type: 'clobber', vreg: 'v0' },
			{ seq: 127, type: 'clobber', vreg: 'v16' },
			{ seq: 128, type: 'clobber', vreg: 'v2' },
			{ seq: 129, type: 'clobber', vreg: 'v5' },
			{ seq: 130, type: 'ir', inst: { alu: { op: 'add', dst: 'v22', lhs: 'v22', rhs: 'v23' } } },
			{ seq: 131, type: 'asm', addr: 0x0044, text: 'add x29, x29, #24', origin: 'lower', parent: 130 },
			{ seq: 132, type: 'ir', inst: { call: { target: 'fib' } } },
			{ seq: 133, type: 'asm', addr: 0x0048, text: 'bl fib', origin: 'lower', parent: 132 },
			{ seq: 134, type: 'ir', inst: { alu: { op: 'sub', dst: 'v24', lhs: 'v24', rhs: 'v25' } } },
			{ seq: 135, type: 'asm', addr: 0x004c, text: 'sub x29, x29, #24', origin: 'lower', parent: 134 },
			{ seq: 136, type: 'define', vreg: 'v26', value: { preg: 'x0' } },
			{ seq: 137, type: 'setslot', vreg: 'v26', region: 'operands', index: 0 },
			{ seq: 138, type: 'ir', inst: { alu: { op: 'le_s', dst: 'v27', lhs: 'v27', rhs: 'v28' } } },
			{ seq: 139, type: 'asm', addr: 0x0050, text: 'subs x28, x28, #8', origin: 'fuse', parent: 138 },
			{ seq: 140, type: 'ir', inst: { br_if: { cond: 'v29', block_if: 'G1', block_else: 'U15' } } },
			{ seq: 141, type: 'asm', addr: 0x0054, text: 'b.gt G1', origin: 'fuse', parent: 140 },

			// ---- G1: suspend ----
			{ seq: 150, type: 'block_start', block: 'G1', successors: [] },
			{ seq: 151, type: 'wasm_op', pc: null, label: 'suspend' },
			{ seq: 152, type: 'ir', inst: 'ret' },
			{ seq: 153, type: 'asm', addr: 0x0058, text: 'ret', origin: 'lower', parent: 152 },

			// ---- U15: add + return ----
			{ seq: 160, type: 'block_start', block: 'U15', successors: [] },
			{ seq: 161, type: 'wasm_op', pc: 16, label: 'local.set.i32 2' },
			{ seq: 162, type: 'clearslot', vreg: 'v26', region: 'operands', index: 0 },
			{ seq: 163, type: 'clearslot', vreg: 'v2', region: 'locals', index: 2 },
			{ seq: 164, type: 'setslot', vreg: 'v26', region: 'locals', index: 2 },
			{ seq: 165, type: 'wasm_op', pc: 17, label: 'local.get.i32 1' },
			{ seq: 166, type: 'setslot', vreg: 'v16', region: 'operands', index: 0 },
			{ seq: 167, type: 'wasm_op', pc: 18, label: 'local.get.i32 2' },
			{ seq: 168, type: 'setslot', vreg: 'v26', region: 'operands', index: 1 },
			{ seq: 169, type: 'wasm_op', pc: 19, label: 'i32.add' },
			{ seq: 170, type: 'clearslot', vreg: 'v26', region: 'operands', index: 1 },
			{ seq: 171, type: 'clearslot', vreg: 'v16', region: 'operands', index: 0 },
			{ seq: 172, type: 'define', vreg: 'v30', value: 'pending' },
			{ seq: 173, type: 'ir', inst: { alu: { op: 'add', dst: 'v30', lhs: 'v16', rhs: 'v26' } } },
			{ seq: 174, type: 'asm', addr: 0x005c, text: 'ldr w2, [x29, #4]', origin: 'regalloc', parent: 173 },
			{ seq: 175, type: 'asm', addr: 0x0060, text: 'add w0, w2, w0', origin: 'lower', parent: 173 },
			{ seq: 176, type: 'setslot', vreg: 'v30', region: 'operands', index: 0 },
			{ seq: 177, type: 'wasm_op', pc: 20, label: 'end (return)' },
			{ seq: 178, type: 'clearslot', vreg: 'v30', region: 'operands', index: 0 },
			{ seq: 179, type: 'clearslot', vreg: 'v5', region: 'fibre', index: 0 },
			{ seq: 180, type: 'resolve', vreg: 'v5' },
			{ seq: 181, type: 'asm', addr: 0x0064, text: 'ldr x30, [sp]', origin: 'regalloc', parent: 180 },
			{ seq: 182, type: 'ir', inst: { alu: { op: 'add', dst: 'v31', lhs: 'v31', rhs: 'v32' } } },
			{ seq: 183, type: 'asm', addr: 0x0068, text: 'add sp, sp, #16', origin: 'lower', parent: 182 },
			{ seq: 184, type: 'ir', inst: 'ret' },
			{ seq: 185, type: 'asm', addr: 0x006c, text: 'ret', origin: 'lower', parent: 184 },
		],
	}],
};
